djangoapi/courses/urls.py
from django.urls import path,include
from . import views
from rest_framework import routers

router = routers.DefaultRouter()
router.register('courses',views.CourseView)

urlpatterns = [
    path('', include(router.urls)),
]

djangoapi/djangoapi/urls.py
from django.contrib import admin
from django.urls import path,include
# from . import views
from rest_framework import routers

router = routers.DefaultRouter()
# router.register('elder',views.CourseView)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls')),
    path('', include(router.urls)),
]

manage_router/urls.py
from django.conf.urls import url
from manage_router import views

app_name = 'manage_router'

urlpatterns = [
    url(r'^$',views.routerListView.as_view(),name='list'),
    url(r'^(?P<pk>\d+)/$',views.routerDetailView.as_view(),name='detail'),
    url(r'^create/$',views.routerCreateView.as_view(),name='create'),
    url(r'^update/(?P<pk>\d+)/$',views.routerUpdateView.as_view(),name='update'),
    url(r'^delete/(?P<pk>\d+)/$',views.routerDeleteView.as_view(),name='delete')
]

trydjango/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from manage_router import views

urlpatterns = [
    url(r'^admin/', admin.site.urls,name='admin'),
    url(r'^$',views.IndexView.as_view()),
    url(r'^manage_router/',include('manage_router.urls',namespace='manage_router')),
    # url(r'^$',views.CBView.as_view()),
    # url(r'^$',views.index)
]

djangoapi/courses/models.py
from django.db import models
class Course(models.Model):
    name = models.CharField(max_length=200)
    language = models.CharField(max_length=100)
    price = models.CharField(max_length=10)

    def __str__(self):
        return self.name

manage_router/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class router(models.Model):
    hostName = models.CharField(max_length=14)

    def __str__(self):
        return self.hostName

    def get_absolute_url(self):
        return reverse("manage_router:detail",kwargs={'pk':self.pk})

class properties(models.Model):
    hostName = models.ForeignKey(router,related_name='routers',on_delete=models.DO_NOTHING)
    sapId = models.CharField(max_length=18)
    loopBack = models.CharField(max_length=4,default="ipv4")
    macAddress = models.CharField(max_length=17)

    def __str__(self):
        return self.sapId

    def get_absolute_url(self):
        return reverse("manage_router:update",kwargs={'pk':self.pk})

djangoapi/courses/views.py
from django.shortcuts import render
from rest_framework import viewsets
from .models import Course
from .serializers import CourseSerializer
# Create your views here.

class CourseView(viewsets.ModelViewSet):
    queryset = Course.objects.all()
    serializer_class = CourseSerializer

manage_router/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.views.generic import (View,TemplateView,
                                ListView,DetailView,
                                CreateView,DeleteView,
                                UpdateView)
from . import models

class IndexView(TemplateView):
    template_name = 'index.html'

class routerListView(ListView):
    context_object_name = 'router_list'
    model = models.router


class routerDetailView(DetailView):
    context_object_name = 'router_details'
    # fields = ("loopBack")
    model = models.properties
    template_name = 'manage_router/router_detail.html'


class routerCreateView(CreateView):
    fields = ("hostName",)
    model = models.router


class routerUpdateView(UpdateView):
    fields = ("sapId","hostName","macAddress")
    model = models.properties
    template_name = 'manage_router/router_form.html'

class routerDeleteView(DeleteView):
    model = models.router
    success_url = reverse_lazy("manage_router:list")

manage_router/templates/manage_router/manage_router_base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>
      {# Title Extensions go inside the block#}
      {% block title_block %}

      {% endblock %}
    </title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'manage_router:list' %}">Routers</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'manage_router:create' %}">Create new Router</a></li>
        </ul>
    </nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>
  </html>

manage_router/templates/manage_router/router_confirm_delete.html
{% extends "manage_router/manage_router_base.html" %}

{% block body_block %}
<h1>Delete {{router.hostName}}?</h1>

<form method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Delete">
  <a href="{% url 'manage_router:detail' pk=router.pk%} ">Cancel</a>

</form>

{% endblock %}

manage_router/templates/manage_router/router_detail.html
{% extends "manage_router/manage_router_base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Detail Page</h1>
    <h2>Details:</h2>
    <p>ID: {{router_details.sapId}}</p>
    <p>loopBack: {{router_details.loopBack}}</p>
    <p>hostName: {{router_details.hostName}}</p>
    <p>macAddress: {{router_details.macAddress}}</p>

  </div>
  <div class="container">
    <p><a class='btn btn-warning' href="{% url 'manage_router:update' pk=router_details.pk %}">Update</a></p>

  </div>

{% endblock %}

manage_router/templates/manage_router/router_form.html
{% extends "manage_router/manage_router_base.html" %}

{% block body_block %}
<h1>
  {% if not form.instance.pk %}
  Create router
  {% else %}
  Update router
  {% endif %}
</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class='btn btn-primary' value="Submit">

  </form>


{% endblock %}

manage_router/templates/manage_router/router_list.html
{% extends "manage_router/manage_router_base.html" %}
{% block body_block %}
  <div class="jumbotron">

    <h1>List of routers!</h1>
      <ol>
        {% for router in router_list %}
          <h2><li><a href="{{router.id}}/">{{router.hostName}} </a></li></h2>
        {% endfor %}
      </ol>

  </div>


{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>
      {# Title Extensions go inside the block#}
      {% block title_block %}

      {% endblock %}
    </title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'manage_router:list' %}">Routers</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="#"></a></li>
        </ul>
    </nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>

  {# Plugins#}


  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script
  src="https://code.jquery.com/jquery-3.2.0.min.js"
  integrity="sha256-JAW99MJVpJBGcbzEuXk4Az05s/XyDdBomFqNlM3ic+I="
  crossorigin="anonymous"></script>
</html>

templates/index.html
{% extends "base.html" %}

  {% block body_block %}
    <div class="jumbotron">
      <h1>Home Page!</h1>
  {% endblock %}